approval_policy = "never"
sandbox_mode = "workspace-write"
model_reasoning_summary = "detailed"

[sandbox_workspace_write]
network_access = false

[windows]
sandbox = "elevated"

[mcp_servers.idea]
url = "http://127.0.0.1:64342/stream"