status = warn
name = VibeComposerLogging

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %date{ISO8601} [%-6.6thread]%-4level: %message%n

appender.debugConsole.type = Console
appender.debugConsole.name = DebugConsole
appender.debugConsole.target = SYSTEM_ERR
appender.debugConsole.follow = true
appender.debugConsole.layout.type = PatternLayout
appender.debugConsole.layout.pattern = %date{ISO8601} [%-6.6thread]%-4level: %message%n

rootLogger.level = debug
rootLogger.appenderRefs = console, debugConsole
rootLogger.appenderRef.console.ref = Console
rootLogger.appenderRef.debugConsole.ref = DebugConsole
